[project]
name = "keepass4crack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pykeepass>=4.1.1.post1",
    "tqdm>=4.67.1",
]
